services:
  - type: web
    name: moneylens-api
    runtime: node
    buildCommand: yarn --frozen-lockfile install; yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PASSWORD
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
